FROM ricejasonf/cppdock:linux_x64 as boost_libraries
    RUN apt-get update -y && apt-get install wget
    WORKDIR /usr/local/src
    RUN wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz \
     && tar -xvzf boost_1_67_0.tar.gz

    WORKDIR /usr/local/src/boost_1_67_0
    RUN mkdir /opt/install/include \
     && cp -R -t /opt/install/include boost

#    RUN  ./bootstrap.sh \
#              --with-toolset=clang \
#              --prefix=/opt/install \
#              --with-libraries=beast \
#     &&  ./b2 clean \
#     &&  ./b2 toolset=clang \ 
#              cxxflags="-std=c++1z -stdlib=libc++" \
#              linkflags="-stdlib=libc++" \
#              --prefix=/opt/install \
#              stage release \
#     &&  ./b2 install \
#              toolset=clang \
#              cxxflags="-std=c++1z -stdlib=libc++" \
#              linkflags="-stdlib=libc++" \
#              --prefix=/opt/install 

FROM ricejasonf/cppdock:linux_x64 as quick_project

    RUN cppdock install_dep linux_x64 0307a4c25eea44330d20a42471c2b43530cfe530 ricejasonf/quick_project 

FROM ricejasonf/cppdock:linux_x64 as build_all

    COPY --from=quick_project /opt/install /usr/local
    RUN cppdock install_dep linux_x64 684dfbd7dfbdd0438ef3670be10002ca33a71715 boostorg/callable_traits 
    RUN cppdock install_dep linux_x64 7cd10e98bde41a2e197138cb423a6f983a66e645 boostorg/hana 
    RUN cppdock install_dep linux_x64 1f52649a1b822c815239788cc528b469b3438985 ricejasonf/full_duplex

FROM ricejasonf/cppdock:linux_x64
    COPY --from=quick_project /opt/install /usr/local
    COPY --from=boost_libraries /opt/install /opt/sysroot
    COPY --from=build_all /opt/install /opt/sysroot

